export const roles = [
  {
    id: 'role-junior-frontend-developer',
    name: 'Junior Frontend Developer',
    slug: 'junior-frontend-developer',
    level: 'junior',
    description:
      'Builds and maintains foundational user-facing web interfaces.',
  },
  {
    id: 'role-frontend-developer',
    name: 'Frontend Developer',
    slug: 'frontend-developer',
    level: 'mid',
    description: 'Builds production-ready responsive web applications.',
  },
  {
    id: 'role-react-developer',
    name: 'React Developer',
    slug: 'react-developer',
    level: 'mid',
    description:
      'Specializes in building React-based applications and component systems.',
  },
  {
    id: 'role-nextjs-developer',
    name: 'Next.js Developer',
    slug: 'nextjs-developer',
    level: 'mid',
    description: 'Builds full-featured React applications using Next.js.',
  },
  {
    id: 'role-ui-engineer',
    name: 'UI Engineer',
    slug: 'ui-engineer',
    level: 'mid',
    description:
      'Focuses on high-quality, accessible and reusable user interfaces.',
  },
  {
    id: 'role-senior-frontend-engineer',
    name: 'Senior Frontend Engineer',
    slug: 'senior-frontend-engineer',
    level: 'senior',
    description: 'Builds and architects scalable frontend applications.',
  },
  {
    id: 'role-frontend-platform-engineer',
    name: 'Frontend Platform Engineer',
    slug: 'frontend-platform-engineer',
    level: 'senior',
    description:
      'Builds shared frontend infrastructure, tooling and developer platforms.',
  },
  {
    id: 'role-full-stack-developer',
    name: 'Full Stack Developer',
    slug: 'full-stack-developer',
    level: 'mid',
    description: 'Builds applications across frontend and backend layers.',
  },
  {
    id: 'role-frontend-tech-lead',
    name: 'Frontend Tech Lead',
    slug: 'frontend-tech-lead',
    level: 'lead',
    description:
      'Leads frontend architecture, technical decisions and engineering practices.',
  },
  {
    id: 'role-frontend-architect',
    name: 'Frontend Architect',
    slug: 'frontend-architect',
    level: 'lead',
    description:
      'Designs large-scale frontend architecture and platform strategy.',
  },
] as const;

export const roleRequirements = [
  // Data are in format of [roleSlug, skillSlug, importance]

  // Junior Frontend Developer
  ['junior-frontend-developer', 'html', 5],
  ['junior-frontend-developer', 'css', 5],
  ['junior-frontend-developer', 'javascript', 5],
  ['junior-frontend-developer', 'responsive-design', 4],
  ['junior-frontend-developer', 'git', 3],
  ['junior-frontend-developer', 'rest-api', 3],
  ['junior-frontend-developer', 'react', 3],

  // Frontend Developer
  ['frontend-developer', 'html', 5],
  ['frontend-developer', 'css', 5],
  ['frontend-developer', 'javascript', 5],
  ['frontend-developer', 'typescript', 4],
  ['frontend-developer', 'react', 4],
  ['frontend-developer', 'responsive-design', 5],
  ['frontend-developer', 'web-accessibility', 4],
  ['frontend-developer', 'rest-api', 4],
  ['frontend-developer', 'git', 4],
  ['frontend-developer', 'web-performance', 3],

  // React Developer
  ['react-developer', 'javascript', 5],
  ['react-developer', 'typescript', 4],
  ['react-developer', 'react', 5],
  ['react-developer', 'react-context', 4],
  ['react-developer', 'redux', 4],
  ['react-developer', 'rest-api', 4],
  ['react-developer', 'react-testing-library', 4],
  ['react-developer', 'git', 4],
  ['react-developer', 'web-performance', 3],

  // Next.js Developer
  ['nextjs-developer', 'javascript', 5],
  ['nextjs-developer', 'typescript', 5],
  ['nextjs-developer', 'react', 5],
  ['nextjs-developer', 'nextjs', 5],
  ['nextjs-developer', 'rest-api', 4],
  ['nextjs-developer', 'web-performance', 4],
  ['nextjs-developer', 'web-accessibility', 3],
  ['nextjs-developer', 'git', 4],
  ['nextjs-developer', 'authentication', 3],

  // UI Engineer
  ['ui-engineer', 'html', 5],
  ['ui-engineer', 'css', 5],
  ['ui-engineer', 'javascript', 4],
  ['ui-engineer', 'react', 4],
  ['ui-engineer', 'responsive-design', 5],
  ['ui-engineer', 'web-accessibility', 5],
  ['ui-engineer', 'design-systems', 5],
  ['ui-engineer', 'tailwind-css', 3],
  ['ui-engineer', 'web-performance', 3],

  // Senior Frontend Engineer
  ['senior-frontend-engineer', 'javascript', 5],
  ['senior-frontend-engineer', 'typescript', 5],
  ['senior-frontend-engineer', 'react', 5],
  ['senior-frontend-engineer', 'nextjs', 3],
  ['senior-frontend-engineer', 'web-accessibility', 4],
  ['senior-frontend-engineer', 'web-performance', 5],
  ['senior-frontend-engineer', 'react-testing-library', 4],
  ['senior-frontend-engineer', 'playwright', 3],
  ['senior-frontend-engineer', 'rest-api', 4],
  ['senior-frontend-engineer', 'frontend-architecture', 5],
  ['senior-frontend-engineer', 'design-systems', 3],
  ['senior-frontend-engineer', 'git', 4],
  ['senior-frontend-engineer', 'code-review', 4],

  // Frontend Platform Engineer
  ['frontend-platform-engineer', 'typescript', 5],
  ['frontend-platform-engineer', 'react', 4],
  ['frontend-platform-engineer', 'vite', 4],
  ['frontend-platform-engineer', 'webpack', 4],
  ['frontend-platform-engineer', 'frontend-architecture', 5],
  ['frontend-platform-engineer', 'design-systems', 4],
  ['frontend-platform-engineer', 'ci-cd', 5],
  ['frontend-platform-engineer', 'docker', 3],
  ['frontend-platform-engineer', 'web-performance', 4],
  ['frontend-platform-engineer', 'git', 4],
  ['frontend-platform-engineer', 'micro-frontends', 4],

  // Full Stack Developer
  ['full-stack-developer', 'javascript', 5],
  ['full-stack-developer', 'typescript', 4],
  ['full-stack-developer', 'react', 4],
  ['full-stack-developer', 'nextjs', 4],
  ['full-stack-developer', 'nodejs', 5],
  ['full-stack-developer', 'rest-api', 5],
  ['full-stack-developer', 'databases', 4],
  ['full-stack-developer', 'authentication', 4],
  ['full-stack-developer', 'git', 4],
  ['full-stack-developer', 'docker', 3],

  // Frontend Tech Lead
  ['frontend-tech-lead', 'typescript', 5],
  ['frontend-tech-lead', 'react', 5],
  ['frontend-tech-lead', 'frontend-architecture', 5],
  ['frontend-tech-lead', 'system-design', 5],
  ['frontend-tech-lead', 'web-performance', 5],
  ['frontend-tech-lead', 'web-accessibility', 4],
  ['frontend-tech-lead', 'design-systems', 4],
  ['frontend-tech-lead', 'code-review', 5],
  ['frontend-tech-lead', 'technical-mentoring', 5],
  ['frontend-tech-lead', 'ci-cd', 4],
  ['frontend-tech-lead', 'frontend-security', 4],
  ['frontend-tech-lead', 'git', 4],

  // Frontend Architect
  ['frontend-architect', 'typescript', 5],
  ['frontend-architect', 'react', 4],
  ['frontend-architect', 'frontend-architecture', 5],
  ['frontend-architect', 'system-design', 5],
  ['frontend-architect', 'micro-frontends', 5],
  ['frontend-architect', 'design-systems', 5],
  ['frontend-architect', 'web-performance', 5],
  ['frontend-architect', 'frontend-security', 5],
  ['frontend-architect', 'ci-cd', 4],
  ['frontend-architect', 'docker', 4],
  ['frontend-architect', 'code-review', 4],
  ['frontend-architect', 'technical-mentoring', 4],
] as const;

export const skills = [
  {
    id: 'skill-html',
    name: 'HTML',
    slug: 'html',
    category: 'Core Web',
    level: 'beginner',
    description: 'Semantic markup for structuring web content.',
  },
  {
    id: 'skill-css',
    name: 'CSS',
    slug: 'css',
    category: 'Core Web',
    level: 'beginner',
    description: 'Styling and layout for web interfaces.',
  },
  {
    id: 'skill-javascript',
    name: 'JavaScript',
    slug: 'javascript',
    category: 'Language',
    level: 'intermediate',
    description: 'Core programming language of the web.',
  },
  {
    id: 'skill-typescript',
    name: 'TypeScript',
    slug: 'typescript',
    category: 'Language',
    level: 'intermediate',
    description: 'Typed JavaScript for scalable applications.',
  },
  {
    id: 'skill-react',
    name: 'React',
    slug: 'react',
    category: 'Framework',
    level: 'intermediate',
    description: 'Component-based library for building user interfaces.',
  },
  {
    id: 'skill-nextjs',
    name: 'Next.js',
    slug: 'nextjs',
    category: 'Framework',
    level: 'intermediate',
    description: 'React framework for production web applications.',
  },
  {
    id: 'skill-vue',
    name: 'Vue',
    slug: 'vue',
    category: 'Framework',
    level: 'intermediate',
    description: 'Progressive JavaScript framework for building interfaces.',
  },
  {
    id: 'skill-angular',
    name: 'Angular',
    slug: 'angular',
    category: 'Framework',
    level: 'intermediate',
    description: 'Full-featured frontend framework.',
  },
  {
    id: 'skill-redux',
    name: 'Redux',
    slug: 'redux',
    category: 'State Management',
    level: 'intermediate',
    description: 'Predictable state management for JavaScript applications.',
  },
  {
    id: 'skill-zustand',
    name: 'Zustand',
    slug: 'zustand',
    category: 'State Management',
    level: 'intermediate',
    description: 'Lightweight React state management library.',
  },
  {
    id: 'skill-react-context',
    name: 'React Context',
    slug: 'react-context',
    category: 'State Management',
    level: 'intermediate',
    description: 'Built-in React mechanism for sharing state.',
  },
  {
    id: 'skill-responsive-design',
    name: 'Responsive Design',
    slug: 'responsive-design',
    category: 'Core Web',
    level: 'intermediate',
    description: 'Building interfaces that adapt across screen sizes.',
  },
  {
    id: 'skill-accessibility',
    name: 'Web Accessibility',
    slug: 'web-accessibility',
    category: 'Core Web',
    level: 'intermediate',
    description: 'Building inclusive and accessible web experiences.',
  },
  {
    id: 'skill-performance',
    name: 'Web Performance',
    slug: 'web-performance',
    category: 'Performance',
    level: 'advanced',
    description: 'Optimizing frontend loading and runtime performance.',
  },
  {
    id: 'skill-browser-apis',
    name: 'Browser APIs',
    slug: 'browser-apis',
    category: 'Core Web',
    level: 'intermediate',
    description: 'Using native browser platform APIs effectively.',
  },
  {
    id: 'skill-tailwind',
    name: 'Tailwind CSS',
    slug: 'tailwind-css',
    category: 'Styling',
    level: 'intermediate',
    description: 'Utility-first CSS framework.',
  },
  {
    id: 'skill-css-modules',
    name: 'CSS Modules',
    slug: 'css-modules',
    category: 'Styling',
    level: 'intermediate',
    description: 'Locally scoped CSS for component-based applications.',
  },
  {
    id: 'skill-sass',
    name: 'Sass',
    slug: 'sass',
    category: 'Styling',
    level: 'intermediate',
    description: 'CSS preprocessor with variables and reusable syntax.',
  },
  {
    id: 'skill-rest',
    name: 'REST API',
    slug: 'rest-api',
    category: 'API',
    level: 'intermediate',
    description: 'Working with RESTful web APIs.',
  },
  {
    id: 'skill-graphql',
    name: 'GraphQL',
    slug: 'graphql',
    category: 'API',
    level: 'intermediate',
    description: 'Query language and runtime for APIs.',
  },
  {
    id: 'skill-websockets',
    name: 'WebSockets',
    slug: 'websockets',
    category: 'API',
    level: 'advanced',
    description: 'Real-time bidirectional browser-server communication.',
  },
  {
    id: 'skill-jest',
    name: 'Jest',
    slug: 'jest',
    category: 'Testing',
    level: 'intermediate',
    description: 'JavaScript testing framework.',
  },
  {
    id: 'skill-vitest',
    name: 'Vitest',
    slug: 'vitest',
    category: 'Testing',
    level: 'intermediate',
    description: 'Fast Vite-native test framework.',
  },
  {
    id: 'skill-testing-library',
    name: 'React Testing Library',
    slug: 'react-testing-library',
    category: 'Testing',
    level: 'intermediate',
    description: 'Testing React components through user behavior.',
  },
  {
    id: 'skill-playwright',
    name: 'Playwright',
    slug: 'playwright',
    category: 'Testing',
    level: 'advanced',
    description: 'End-to-end testing across modern browsers.',
  },
  {
    id: 'skill-cypress',
    name: 'Cypress',
    slug: 'cypress',
    category: 'Testing',
    level: 'advanced',
    description: 'Browser-based end-to-end testing framework.',
  },
  {
    id: 'skill-git',
    name: 'Git',
    slug: 'git',
    category: 'Tooling',
    level: 'beginner',
    description: 'Distributed version control system.',
  },
  {
    id: 'skill-npm',
    name: 'npm',
    slug: 'npm',
    category: 'Tooling',
    level: 'beginner',
    description: 'JavaScript package manager.',
  },
  {
    id: 'skill-vite',
    name: 'Vite',
    slug: 'vite',
    category: 'Tooling',
    level: 'intermediate',
    description: 'Modern frontend build tool.',
  },
  {
    id: 'skill-webpack',
    name: 'Webpack',
    slug: 'webpack',
    category: 'Tooling',
    level: 'advanced',
    description: 'Module bundler for JavaScript applications.',
  },
  {
    id: 'skill-design-systems',
    name: 'Design Systems',
    slug: 'design-systems',
    category: 'Architecture',
    level: 'advanced',
    description: 'Reusable standards and components for product interfaces.',
  },
  {
    id: 'skill-frontend-architecture',
    name: 'Frontend Architecture',
    slug: 'frontend-architecture',
    category: 'Architecture',
    level: 'advanced',
    description: 'Designing scalable frontend application structures.',
  },
  {
    id: 'skill-system-design',
    name: 'System Design',
    slug: 'system-design',
    category: 'Architecture',
    level: 'advanced',
    description: 'Designing scalable software systems and boundaries.',
  },
  {
    id: 'skill-micro-frontends',
    name: 'Micro Frontends',
    slug: 'micro-frontends',
    category: 'Architecture',
    level: 'advanced',
    description:
      'Splitting large frontend systems into independently owned applications.',
  },
  {
    id: 'skill-nodejs',
    name: 'Node.js',
    slug: 'nodejs',
    category: 'Backend',
    level: 'intermediate',
    description: 'JavaScript runtime for server-side applications.',
  },
  {
    id: 'skill-databases',
    name: 'Databases',
    slug: 'databases',
    category: 'Backend',
    level: 'intermediate',
    description: 'Understanding persistence and database fundamentals.',
  },
  {
    id: 'skill-authentication',
    name: 'Authentication',
    slug: 'authentication',
    category: 'Backend',
    level: 'intermediate',
    description: 'Implementing secure identity and access flows.',
  },
  {
    id: 'skill-cicd',
    name: 'CI/CD',
    slug: 'ci-cd',
    category: 'DevOps',
    level: 'advanced',
    description: 'Automating build, testing and deployment pipelines.',
  },
  {
    id: 'skill-docker',
    name: 'Docker',
    slug: 'docker',
    category: 'DevOps',
    level: 'advanced',
    description: 'Containerizing applications and development environments.',
  },
  {
    id: 'skill-code-review',
    name: 'Code Review',
    slug: 'code-review',
    category: 'Engineering',
    level: 'advanced',
    description: 'Reviewing code for correctness, maintainability and quality.',
  },
  {
    id: 'skill-mentoring',
    name: 'Technical Mentoring',
    slug: 'technical-mentoring',
    category: 'Engineering',
    level: 'advanced',
    description: 'Helping engineers improve through technical guidance.',
  },
  {
    id: 'skill-security',
    name: 'Frontend Security',
    slug: 'frontend-security',
    category: 'Engineering',
    level: 'advanced',
    description: 'Preventing common security issues in frontend applications.',
  },
] as const;

export const prerequisites = [
  // Data are in format of [sourceSkill, targetSkill]

  ['html', 'web-accessibility'],
  ['html', 'react'],

  ['css', 'responsive-design'],
  ['css', 'tailwind-css'],
  ['css', 'css-modules'],
  ['css', 'sass'],

  ['javascript', 'typescript'],
  ['javascript', 'react'],
  ['javascript', 'vue'],
  ['javascript', 'angular'],
  ['javascript', 'nodejs'],
  ['javascript', 'browser-apis'],

  ['typescript', 'frontend-architecture'],

  ['react', 'nextjs'],
  ['react', 'react-context'],
  ['react', 'redux'],
  ['react', 'zustand'],
  ['react', 'react-testing-library'],
  ['react', 'design-systems'],

  ['rest-api', 'authentication'],

  ['react-testing-library', 'playwright'],
  ['react-testing-library', 'cypress'],

  ['git', 'ci-cd'],

  ['frontend-architecture', 'micro-frontends'],
  ['frontend-architecture', 'system-design'],

  ['nodejs', 'databases'],

  ['ci-cd', 'docker'],
] as const;

export const relatedSkills = [
  // Data are in format of [sourceSkill, targetSkill]
  ['react', 'nextjs'],
  ['react', 'redux'],
  ['react', 'zustand'],
  ['react', 'react-context'],

  ['jest', 'vitest'],
  ['playwright', 'cypress'],
  ['jest', 'react-testing-library'],
  ['vitest', 'react-testing-library'],

  ['tailwind-css', 'css-modules'],
  ['tailwind-css', 'sass'],

  ['rest-api', 'graphql'],
  ['rest-api', 'websockets'],

  ['vite', 'webpack'],

  ['design-systems', 'web-accessibility'],
  ['design-systems', 'frontend-architecture'],

  ['web-performance', 'browser-apis'],

  ['frontend-architecture', 'system-design'],
  ['frontend-architecture', 'micro-frontends'],

  ['ci-cd', 'docker'],

  ['code-review', 'technical-mentoring'],
] as const;
